# Autogenerated by nbdev

d = { 'settings': { 'branch': '{branch}',
                'doc_baseurl': '/mysd/',
                'doc_host': 'https://{user}.github.io',
                'git_url': 'https://github.com/{user}/mysd/tree/{branch}/',
                'lib_path': 'mysd'},
  'syms': { 'mysd.main': { 'mysd.main.latents_to_pil': ('main.html#latents_to_pil', 'mysd/main.py'),
                           'mysd.main.loop': ('main.html#loop', 'mysd/main.py'),
                           'mysd.main.pil_to_latent': ('main.html#pil_to_latent', 'mysd/main.py'),
                           'mysd.main.predict': ('main.html#predict', 'mysd/main.py'),
                           'mysd.main.random_latents': ('main.html#random_latents', 'mysd/main.py'),
                           'mysd.main.select_cuda': ('main.html#select_cuda', 'mysd/main.py'),
                           'mysd.main.text2vector': ('main.html#text2vector', 'mysd/main.py')}}}